// resume-editor-frontend/components/organisms/CareerTable/DocumentBody.tsx
import { useMemo } from "react";
import { MarkdownDocument } from "@/components/atoms/MarkdownDocument";

type Props = {
  label: string;
  document: string;
};

export const DocumentBody = ({ label, document }: Props) => {
  return (
    <tbody>
      <tr>
        <th className="p-2" colSpan={2}>
          {label}
        </th>
        <td className="p-4 align-top" colSpan={3}>
          <MarkdownDocument document={document} />
        </td>
      </tr>
    </tbody>
  );
};

// resume-editor-backend/src/vue-server-renderer/components/presets/organisms/CareerTable/DocumentBody.vue
<script setup lang="ts">
defineProps<{
  label: string;
  markdownPath: string;
}>();
</script>

<template>
  <tbody>
    <tr>
      <th class="p-2" colspan="2">{{ label }}</th>
      <td class="p-4 align-top" colspan="3">
        <MarkdownDocument :path="markdownPath" />
      </td>
    </tr>
  </tbody>
</template>
